### PR TITLE
feat: Remove custom event metrics

### PR DESCRIPTION
**Pull request by nicholascapo**
* The registration of metrics was in an init() function which
  runs before main() and before the viper option "enable-prometheus" is
  configured, meaning that the metrics would never be registered
* This has been broken since 2022-09-01 (de151a37e81756388f938524f594300d223a2492),
  so even though this is not a backwards compatible change,
  removing the metrics won't break anything recent
* In addition, the labels on the custom metrics have very high cardinality,
  which causes increasing (possibly unbounded) memory usage over time
* All of this means we should just remove the metrics entirely

Signed-off-by: Nicholas Capo <nicholas@capo.tech>

### CODE REVIEW

**Review by jan--f — COMMENTED** [review]
Dropping the `involved_object_name` is definitely a good decision.
I don't have deep insight here but I'd encourage to reconsider the `reason` label as well. Since reasons are not really standardized, this label has the potential to cause high cardinality and thus memory consumption. Though I acknowledge that its unlikely the value set for `reason` grows continuously during a clusters lifetime. So if the label is useful, feel free to keep it.

**Comment by jcantrill** [comment]
> Dropping the `involved_object_name` is definitely a good decision. I don't have deep insight here but I'd encourage to reconsider the `reason` label as well. Since reasons are not really standardized, this label has the potential to cause high cardinality and thus memory consumption. Though I acknowledge that its unlikely the value set for `reason` grows continuously during a clusters lifetime. So if the label is useful, feel free to keep it.

Is there value in the metrics without "reason"?

**Comment by nicholascapo** [comment]
> > Dropping the `involved_object_name` is definitely a good decision. I don't have deep insight here but I'd encourage to reconsider the `reason` label as well. Since reasons are not really standardized, this label has the potential to cause high cardinality and thus memory consumption. Though I acknowledge that its unlikely the value set for `reason` grows continuously during a clusters lifetime. So if the label is useful, feel free to keep it.
> 
> Is there value in the metrics without "reason"?

I think the `reason` is useful.
But for me specifically, I'm using Loki so I can easily get the rate of log events, sliced by any field/label, so honestly these custom metrics aren't very important.

Could we remove the custom metrics completely?
They have been broken for more than a year, so not really a breaking change, and removing them also removes the possibility of unbounded memory usage.

**Comment by jcantrill** [comment]
>Could we remove the custom metrics completely?
They have been broken for more than a year, so not really a breaking change, and removing them also removes the possibility of unbounded memory usage.

Internal discussion the result was "yes".  Please adjust the PR and lets drop the custom metrics entirely

**Comment by nicholascapo** [comment]
@jcantrill done. Ready for review

**Comment by nicholascapo** [comment]
@jcantrill @jan--f How can I request a new release to include these changes? `eventrouter` is still leaking memory in my environments.

**Comment by jcantrill** [comment]
> @jcantrill @jan--f How can I request a new release to include these changes? `eventrouter` is still leaking memory in my environments.

How do you consume this image now?  We released a logging 5.8.0 version a few weeks ago which would include this change

**Comment by nicholascapo** [comment]
Ah, I thought we were using a pre-built docker image, but since we don't have access to `registry.redhat.io/openshift-logging/eventrouter-rhel8` we are building from source.

Currently we are building from the `release-5.7` tag.
Does this repo not get tagged on releases anymore?

**Comment by nicholascapo** [comment]
Ah! I'll use the images from quay.
Thanks!

**Pull request merged**
