### PR TITLE
Update go to 1.18 and k8s library to v0.24.3

### PR DESCRIPTION
**Pull request by Red-GV**
This PR updates the golang version to 1.18 and the kubernetes libraries to v0.24.3.

### CODE REVIEW

**Comment by jcantrill** [comment]
This requires additional changes to the CI and the Dockerfile

**Comment by Red-GV** [comment]
Yeah, I just realized. I'll hold off on this PR then until the go 1.18 toolset is available from the ubi8 image.

**Comment by Red-GV** [comment]
Think with the effort for #33 , we can continue with this one. @jcantrill

**Pull request merged**
