### PR TITLE
Upgrade to v0.2 

### PR DESCRIPTION
**Pull request by nhosoi**
Merged https://github.com/heptiolabs/eventrouter tag v0.2, then applied our v0.1 patches on top of it.

### CODE REVIEW

**Comment by richm** [comment]
Marked as needs rebase?

**Comment by nhosoi** [comment]
> Marked as needs rebase?

git/github did not like the change order I took... :p  I rebased and fixed the conflicts.

**Comment by richm** [comment]
@nhosoi have you tested this with logging?

**Comment by nhosoi** [comment]
> have you tested this with logging?

No, not yet.  The issue is it seems "oct sync" does not carry the submodule reference if it's not the origin repo.

```
$ git submodule update
fatal: reference is not a tree: fd97150b7502216a2a9d8aae0b81b380a9123ebb
Unable to checkout 'fd97150b7502216a2a9d8aae0b81b380a9123ebb' in submodule path 'eventrouter'
```
And I looked into these files on the test host, they were not from my test branch. :(
`.git/modules/eventrouter/{config,FETCH_HEAD,HEAD,packed-refs}`

**Comment by nhosoi** [comment]
I could successfully run the logging CI-tests including the eventrouter test suite with this PR branch.
```
# git submodule
 e6b3777558173b4554a92e7e23ac27ca43c853bd eventrouter (v0.1-27-ge6b3777)
```
No regression was observed.
```
[INFO] Logging test suite test-eventrouter started at Fri Oct  5 20:50:28 UTC 2018
[INFO] Logging test suite test-eventrouter succeeded at Fri Oct  5 20:51:27 UTC 2018
```

**Comment by richm** [comment]
```
[INFO] Logging test suite test-eventrouter started at Fri Oct  5 20:50:28 UTC 2018
[INFO] Logging test suite test-eventrouter succeeded at Fri Oct  5 20:51:27 UTC 2018
```
Were there any messages between these two? Right now the eventrouter test is disabled - `[WARNING] Eventrouter not deployed`

**Comment by richm** [comment]
@jcantrill ready to merge?  looks like I can merge in the github UI

**Pull request merged**
