### PR TITLE
Updated vendor dir to match go.mod

### PR DESCRIPTION
**Pull request by syedriko**
Updated vendor directory to match go.mod so the eventrouter can be built with Cachito

JIRA: https://issues.redhat.com/browse/LOG-2248

### CODE REVIEW

**Comment by jcantrill** [comment]
Why would we add files to the vendor dir instead of just removing the vendor directly entirely.  It was my understanding we only need go.mod and go.sum

**Comment by syedriko** [comment]
I wasn't sure what was decided and took the safe route. Have we decided to drop the vendor dir?

**Comment by jcantrill** [comment]
> I wasn't sure what was decided and took the safe route. Have we decided to drop the vendor dir?

IMO i think dropping the vendor directory is better. This seems like a good repo for experimenting.

**Comment by alanconway** [comment]
@syedriko +1 to dropping vendor. In the long run it'll be simpler, so even if we have to iron out some wrinkles to make it work IMO it is worth it.

**Pull request merged**
